name: remove_video_location
description: "Strip location and related metadata from video files without re-encoding."
version: 0.9.1
repository: https://github.com/Shawn-sudo/remove_video_location
issue_tracker: https://github.com/Shawn-sudo/remove_video_location/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.remove_video_location
        pluginClass: RemoveVideoLocationPlugin
      ios:
        pluginClass: RemoveVideoLocationPlugin
